import {
  ShoppingCart,
  UtensilsCrossed,
  Car,
  Heart,
  Gamepad2,
  GraduationCap,
  Briefcase,
  TrendingUp,
  Gift,
  Landmark,
  Home,
  Wifi,
  Smartphone,
  Shirt,
  Plane,
  Music,
  Dumbbell,
  Baby,
  PawPrint,
  Wrench,
  Pill,
  BookOpen,
  Coffee,
  Fuel,
  CreditCard,
  Wallet,
  PiggyBank,
  HandCoins,
  Receipt,
  CircleDollarSign,
  Tag,
  BriefcaseMedical,
  Utensils,
} from "lucide-react-native";
import type { LucideIcon } from "lucide-react-native";

const ICON_MAP: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  car: Car,
  heart: Heart,
  "gamepad-2": Gamepad2,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  "briefcase-medical": BriefcaseMedical,
  "trending-up": TrendingUp,
  gift: Gift,
  landmark: Landmark,
  home: Home,
  wifi: Wifi,
  smartphone: Smartphone,
  shirt: Shirt,
  plane: Plane,
  music: Music,
  dumbbell: Dumbbell,
  baby: Baby,
  "paw-print": PawPrint,
  wrench: Wrench,
  pill: Pill,
  "book-open": BookOpen,
  coffee: Coffee,
  fuel: Fuel,
  "credit-card": CreditCard,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  "hand-coins": HandCoins,
  receipt: Receipt,
  "circle-dollar-sign": CircleDollarSign,
  tag: Tag,
};

export function getIconComponent(iconName: string): LucideIcon {
  return ICON_MAP[iconName] ?? Tag;
}

export const AVAILABLE_ICONS = Object.keys(ICON_MAP);
